### ISSUE TITLE
VizHub 3 Runtime

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub-legacy#507]
As part of the VizHub 3 rewrite, the VizHub Runtime should be partitioned off as a standalone module / chunk of work.

Requirements:
 * Feature parity with VizHub 2 runtime (HTML, CSS, JS, ES Modules, JSX, NPM packages)
 * Ability to import modules exported from other vizzes (Composition)
 * A new "mode" that support hot reloading of JavaScript (initial prototype here: [experimental-runtime](https://github.com/curran/experimental-runtime)).
 * Hot reloading of CSS
 * Support for dynamic state/configuration that lives outside of the code (State) (initial prototype here: [experimental-runtime](https://github.com/curran/experimental-runtime))
   * A program needs to be able to recieve state updates as they happen, without re-running the entire HTML page
   * A program needs to be able to write state updates (e.g. in response to user interaction)

**Comment by nitanagdeote** [comment]
Remove me from here

**Comment by curran** [comment]
You can change your "watching" settings in GitHub. I cannot do it for you.

![image](https://user-images.githubusercontent.com/68416/151412411-56b0cef9-9aed-4764-a21c-8760b254eb2d.png)

**Comment by curran** [comment]
Awesome related work https://roadtolarissa.com/hot-reload/

https://github.com/1wheel/hot-server/blob/master/index.js
